### ISSUE TITLE
A segmentation fault

### ISSUE THREAD

**Issue by jpcima** [jpcima/midiplay#15]
```
#11 0x0000561c765115db in Midi_Synth_Instrument::audio_callback(float*, unsigned int, void*)
    (output=0x40, nframes=2348887296, user_data=0x7fda8c03ab80) at sources/player/instrument.cc:284
#12 0x0000561c76514c64 in Audio_Device::process_cycle(float*, unsigned int)
    (this=0x7fda8c0021b0, output=0x7fda8c012010, nframes=512) at sources/player/adev/adev.cc:45
#13 0x0000561c76515201 in Audio_Device_Jack::jack_audio_callback(unsigned int, void*) (nframes=512, user_data=0x7fda8c0021b0)
    at sources/player/adev/adev_jack.cc:81
```

**Comment by jpcima** [comment]
It happened while opening another JACK client as the synth played in the background.
